name = "openhub"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "DB"
database_name = "openhub"
database_id = "e7c27707-7f65-45ef-866d-d234a9b8feb8"

[[r2_buckets]]
binding = "R2"
bucket_name = "openhub-assets"
